---
settings:
  name: Cloud Volumes Service for Google Cloud
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Cloud Volumes Service für Google Cloud Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über Cloud Volumes Service für Google Cloud
      url: "/concept-cvs-gcp.html"
    - title: Erste Schritte für den Workflow
      url: "/task-quick-start.html"
    - title: Google Cloud einrichten
      url: "/task-set-up-google-cloud.html"
    - title: Schaffen Sie eine Arbeitsumgebung
      url: "/task-create-working-env.html"
  - title: Nutzen Sie Cloud Volumes Service für Google Cloud
    entries:
    - title: Erstellung und Mounten von Volumes
      url: "/task-create-volumes.html"
    - title: Management vorhandener Volumes
      url: "/task-manage-volumes.html"
    - title: Managen von Cloud Volumes Snapshots
      url: "/task-manage-snapshots.html"
    - title: Managen Sie Ihre Active Directory-Konfiguration
      url: "/task-manage-active-directory.html"
    - title: Entfernen Sie Cloud Volumes Service
      url: "/task-remove-working-env.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
